# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='image_src',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
