# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landspace_web', '0003_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Step'),
        ),
    ]
