# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landspace_web', '0004_auto_20170203_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='registration_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
