# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landspace_web', '0005_client_registration_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_registered',
            field=models.BooleanField(default=False),
        ),
    ]
