# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landspace_web', '0009_auto_20170225_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_mailing_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='is_showcase_project',
            field=models.BooleanField(default=False),
        ),
    ]
