# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landspace_web', '0010_auto_20170413_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_active_project',
            field=models.BooleanField(default=False),
        ),
    ]
