# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='next',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Step'),
        ),
        migrations.AddField(
            model_name='step',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
