# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170202_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='icon_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
