# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170213_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address_1',
            field=models.CharField( max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='address_2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='approximate_budget',
            field=models.CharField(choices=[('$500 - $1,000', '$500 - $1,000'), ('$1,000 - $5,000', '$1,000 - $5,000'), ('$5000 - $10,000', '$5000 - $10,000'), ('$10,000 - $20,000', '$10,000 - $20,000'), ('$20,000 - $50,000', '$20,000 - $50,000'), ('$50,000 - $100,000', '$50,000 - $100,000'), ('$100,000+', '$100,000+')],  max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='has_edible_garden',
            field=models.CharField(choices=[('herbs (small pots - vertical)', ' herbs (small pots - vertical)'), ('vegetables (raised planter boxes)', ' vegetables (raised planter boxes)'), ('fruit trees', ' fruit trees'), ('not for my space', ' not for my space')],  max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='has_pets',
            field=models.CharField(choices=[('dog', 'dog'), ('cat', 'cat'), ('reptile', 'reptile'), ('tiger', 'tiger'), ('other', 'other'), ('no', 'no')],  max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_in_phases',
            field=models.CharField(choices=[('yes - I will build them when I have the time', 'yes - I will build them when I have the time'), ('no - let\u2019s get this all out in one shot ', 'no - let\u2019s get this all out in one shot ')],  max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='lot_size',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')],  max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='primary_users',
            field=models.CharField(choices=[('just me.', 'just me.'), ('my partner and I', 'my partner and I'), ('my family with young kids', 'my family with young kids'), ('my family with young adults', 'my family with young adults'), ('my family with elderly adults', 'my family with elderly adults'), ('my friends and I', 'my friends and I'), ('other', 'other')],  max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(choices=[('front yard', 'front yard'), ('backyard', 'backyard'), ('small garden area', 'small garden area'), ('deck or patio', 'deck or patio'), ('roofdeck', 'roofdeck'), ('other', 'other')],  max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_description_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='requires_contractor',
            field=models.CharField(choices=[('yes', 'yes'), ('no - I will be diy-ing this project', 'no - I will be diy-ing this project'), ('no - I already have a good contractor', 'no - I already have a good contractor'), ('no - I am not planning on building just yet', 'no - I am not planning on building just yet')],  max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slope_amount',
            field=models.CharField(choices=[('None, the space is flat', 'None, the space is flat'), ('Some, moderate grade change', 'Some, moderate grade change'), ('A lot, steep slopes', 'A lot, steep slopes')],  max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='state_province',
            field=models.CharField( max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='timeline',
            field=models.CharField( max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='work_type',
            field=models.CharField(choices=[('planting', 'planting'), ('wood construction', 'wood construction'), ('stonework or masonry', 'stonework or masonry'), ('walls', 'walls'), ('art installation', 'art installation'), ('small improvements (pots, firepit, etc)', 'small improvements (pots, firepit, etc)'), ('patio', 'patio'), ('pool or hot tub', 'pool or hot tub'), ('fountain', 'fountain'), ('pond', 'pond'), ('outdoor kitchen', 'outdoor kitchen'), ('playspace', 'playspace'), ('habitat creation', 'habitat creation'), ('I don\u2019t have a set plan yet. I am looking for a designer to assist me', 'I don\u2019t have a set plan yet. I am looking for a designer to assist me'), ('other', 'other')],  max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='zip_code',
            field=models.CharField( max_length=5),
            preserve_default=False,
        ),
    ]
