# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landspace_web', '0005_client_registration_url'),
        ('projects', '0009_auto_20170216_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='project_type',
        ),
        migrations.AddField(
            model_name='project',
            name='accessibility_concerns',
            field=models.CharField(choices=[('yes wheelchair access is important', 'yes wheelchair access is important'), ('no', 'no')], max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='has_allergies',
            field=models.CharField(choices=[('nope all good!', 'nope all good!'), ('yes I will explain on the call with my designer', 'yes I will explain on the call with my designer')], max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='has_existing_plan',
            field=models.CharField(choices=[('yes I will upload them when I upload images', 'yes I will upload them when I upload images'), ('no I am a blank canvas', 'no I am a blank canvas')], max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_for_sports',
            field=models.CharField(choices=[('no', 'no'), ('bocce', 'bocce'), ('basketball', 'basketball'), ('horseshoes', 'horseshoes'), ('open lawn for free play', 'open lawn for free play'), ('other', 'other')], max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='outdoor_cooking_level',
            field=models.CharField(choices=[('none, we cook inside', 'none, we cook inside'), ('space for a pre-fab bbq grill', 'space for a pre-fab bbq grill'), ('built-in outdoor kitchen', 'built-in outdoor kitchen'), ('custom brick oven', 'custom brick oven')], max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='preferred_designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landspace_web.Designer'),
        ),
        migrations.AddField(
            model_name='project',
            name='start',
            field=models.CharField(choices=[('now', 'now'), ('in a few months', 'in a few months'), ('several months', 'several months'), ('not sure, just checking my options', 'not sure, just checking my options')], max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='has_pets',
            field=models.CharField(choices=[('dog', 'dog'), ('cat', 'cat'), ('reptile', 'reptile'), ('horse', 'horse'), ('tiger', 'tiger'), ('other', 'other'), ('no', 'no')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='lot_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='work_type',
            field=models.CharField(choices=[('planting', 'planting'), ('wood construction', 'wood construction'), ('stonework or masonry', 'stonework or masonry'), ('walls', 'walls'), ('art installation', 'art installation'), ('small improvements (pots, firepit, etc)', 'small improvements (pots, firepit, etc)'), ('patio', 'patio'), ('pool or hot tub', 'pool or hot tub'), ('fountain', 'fountain'), ('pond', 'pond'), ('outdoor kitchen', 'outdoor kitchen'), ('playspace', 'playspace'), ('earthwork', 'earthwork'), ('wood construction (deck, pergola, etc.)', 'wood construction (deck, pergola, etc.)'), ('rooftop', 'rooftop'), ('sports court', 'sports court'), ('I don\u2019t have a set plan yet. I am looking for a designer to assist me', 'I don\u2019t have a set plan yet. I am looking for a designer to assist me'), ('other', 'other')], max_length=100),
        ),
    ]
