# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170220_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='timeline',
        ),
        migrations.AddField(
            model_name='project',
            name='admin_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_project', to='projects.Step'),
        ),
        migrations.AddField(
            model_name='project',
            name='designer_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_project', to='projects.Step'),
        ),
        migrations.AlterField(
            model_name='project',
            name='accessibility_concerns',
            field=models.CharField(choices=[('yes wheelchair access is important', 'yes wheelchair access is important'), ('no', 'no')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='approximate_budget',
            field=models.CharField(choices=[('$500 - $1,000', '$500 - $1,000'), ('$1,000 - $5,000', '$1,000 - $5,000'), ('$5000 - $10,000', '$5000 - $10,000'), ('$10,000 - $20,000', '$10,000 - $20,000'), ('$20,000 - $50,000', '$20,000 - $50,000'), ('$50,000 - $100,000', '$50,000 - $100,000'), ('$100,000+', '$100,000+')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_allergies',
            field=models.CharField(choices=[('nope all good!', 'nope all good!'), ('yes I will explain on the call with my designer', 'yes I will explain on the call with my designer')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_edible_garden',
            field=models.CharField(choices=[('herbs (small pots - vertical)', ' herbs (small pots - vertical)'), ('vegetables (raised planter boxes)', ' vegetables (raised planter boxes)'), ('fruit trees', ' fruit trees'), ('not for my space', ' not for my space')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_existing_plan',
            field=models.CharField(choices=[('yes I will upload them when I upload images', 'yes I will upload them when I upload images'), ('no I am a blank canvas', 'no I am a blank canvas')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_pets',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_for_sports',
            field=models.CharField(choices=[('no', 'no'), ('bocce', 'bocce'), ('basketball', 'basketball'), ('horseshoes', 'horseshoes'), ('open lawn for free play', 'open lawn for free play'), ('other', 'other')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_in_phases',
            field=models.CharField(choices=[('yes - I will build them when I have the time', 'yes - I will build them when I have the time'), ('no - let\u2019s get this all out in one shot ', 'no - let\u2019s get this all out in one shot ')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='outdoor_cooking_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_users',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='requires_contractor',
            field=models.CharField(choices=[('yes', 'yes'), ('no - I will be diy-ing this project', 'no - I will be diy-ing this project'), ('no - I already have a good contractor', 'no - I already have a good contractor'), ('no - I am not planning on building just yet', 'no - I am not planning on building just yet')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='slope_amount',
            field=models.CharField(choices=[('None, the space is flat', 'None, the space is flat'), ('Some, moderate grade change', 'Some, moderate grade change'), ('A lot, steep slopes', 'A lot, steep slopes')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.CharField(choices=[('now', 'now'), ('in a few months', 'in a few months'), ('several months', 'several months'), ('not sure, just checking my options', 'not sure, just checking my options')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='work_type',
            field=models.CharField(max_length=100),
        ),
    ]
