# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20170304_1219'),
    ]

    operations = [
        migrations.RunSQL("update projects_project set designer_id = null where 1=1;"),
        migrations.AlterField(
            model_name='project',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_project', to='landspace_web.Designer'),
        ),
    ]
