# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20170304_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='drive_folder',
            field=models.URLField(blank=True, null=True),
        ),
    ]
