# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_drive_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='modal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
