# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_step_modal'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
